      PROGRAM RTIOSCHWENKE
C     READS ENERGY LEVEL DATA IN ASCII FOR 5 ISOTOPES FOR SCHWENKE'S TIO LINELIST
C     WRITES ONE BINARY FILE
      REAL*4 XJ(269300)
      REAL*8 E(269300,5),STATE(269300,5)
C     READS ETIOSCHWENKE46.ASC
C     READS ETIOSCHWENKE47.ASC
C     READS ETIOSCHWENKE48.ASC
C     READS ETIOSCHWENKE49.ASC
C     READS ETIOSCHWENKE50.ASC
      DO 9 ILEVEL=1,269300
    8 FORMAT(F11.5,I3,A5,3x,E10.3)
      READ(11,8)E(ILEVEL,1),J,STATE(ILEVEL,1),ASUM
      READ(12,8)E(ILEVEL,2),J,STATE(ILEVEL,2),ASUM
      READ(13,8)E(ILEVEL,3),J,STATE(ILEVEL,3),ASUM
      READ(14,8)E(ILEVEL,4),J,STATE(ILEVEL,4),ASUM
      READ(15,8)E(ILEVEL,5),J,STATE(ILEVEL,5),ASUM
      XJ(ILEVEL)=J
    9 CONTINUE
C     WRITES ETIOSCHWENKE.BIN
      WRITE(7)E,XJ,STATE    
      CALL EXIT
      END  
